<i class="material-icons character-Close">clear</i>
<h1>Terms and Conditions</h1>
<div class="AgreementText">
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzc bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzc
    <br/>
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzc
    <br/>
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
    bjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfdsfsdfsdfsdfsavcvzcbjkbkjsbjkgbbgsbjfsdafdsgfdgsdfadfdfafdafsdfsdfsdfds
</div>
<div class="YesAgreement">
    <p>Do Not Agree</p>
    <span>Agree</span>
</div>
@section('content')
@endsection
